spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookproject?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT&rewriteBatchedStatements=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.mchange.v2.c3p0.DriverManagerDataSource